### ISSUE TITLE
Is this code only implemented DQN version? 

### ISSUE THREAD

**Issue by JunningHuang** [Kaixhin/Rainbow#10]
Hi, I figure out that this code is only implemented dqn, not ddqn or rainbow. Can you provide a ddqn version for me? Mail: jn8227805@gmail.com

**Comment by Kaixhin** [comment]
This code currently implements all of the methods listed in [Rainbow](https://arxiv.org/abs/1710.02298), which includes relevant changes for the Double Q-learning update [here](https://github.com/Kaixhin/Rainbow/blob/master/agent.py#L55-L59).
