### ISSUE TITLE
Updating Priorities with Importance Weighted Loss instead of TD-Error

### ISSUE THREAD

**Issue by nasimrahaman** [Kaixhin/Rainbow#24]
In [this line](https://github.com/Kaixhin/Rainbow/blob/master/agent.py#L89), the priorities are updated with the importance sampled weights (see [this line](https://github.com/Kaixhin/Rainbow/blob/master/agent.py#L83)). This does not appear to be consistent with algorithm 1 of [Schaul et al. 2016](https://arxiv.org/abs/1511.05952) - is this intentional? 

P.S. great work!

**Comment by Kaixhin** [comment]
This is indeed intentional and based on personal correspondence - I've added a comment there and put a note in the repo wiki to reflect this. I don't actually know how much impact this has though, and I don't have the resources to test the differences.
