### ISSUE TITLE
Please create documentation for --render

### ISSUE THREAD

**Issue by jkterry1** [Kaixhin/Rainbow#46]
Title stands- I'd very much like to be able to watch the trained agent play, and I haven't been able to figure out how to make it do that after spending half an hour looking through the code

Edit:
Can --render actually do anything? You use atari-py not gym, and only gym supports rendering: https://github.com/openai/atari-py/issues/14

**Comment by Kaixhin** [comment]
The help string currently reads `'Display screen (testing only)'`. It training normally, it renders a display during the testing phase (run at a frequency determined by `--evaluation-interval`), or when just running evaluation (`--evaluate`).

The `render` function for the environment can be found [here](https://github.com/Kaixhin/Rainbow/blob/master/env.py#L89-L91).
