### ISSUE TITLE
Zero-filling tensors to reset state buffer

### ISSUE THREAD

**Issue by ThisIsIsaac** [Kaixhin/Rainbow#47]
In [env.py](https://github.com/Kaixhin/Rainbow/blob/master/env.py#L31), you clear `state_buffer` by enqueuing empty zero-filled tensors:

```python
for _ in range(self.window):
      self.state_buffer.append(torch.zeros(84, 84, device=self.device))
```
I see how this would work if we are dealing with an environment where the state is a screen and each value in the tensor is an RGB value. However, can zero-filling a tensor to indicate the non-existance of state be generalized to other environments? For example, if each value in the tensor means "waiting time of a customer" then, would this approach also work?

**Comment by Kaixhin** [comment]
This may/may not work - you'd have to devise an appropriate "null" value for your domain (maybe -1 makes more sense than 0 for wait time, I don't know), though in the end you may just have to try a few options and see what works best empirically.
