### ISSUE TITLE
properly notify & raise errors on loading pretrained models

### ISSUE THREAD

**Issue by ThisIsIsaac** [Kaixhin/Rainbow#50]
when I accidently gave incorrect model path:`python main.py --model wrong/path`, I wasn't able to catch this until too late. To avoid such mistakes, I've added a check to properly throw error if the file provided is missing. Also, I thought it'd be nice to be notified whether the training is starting from scratch or from model ( since there is really no way to figure out if the model is loaded properly without a print statement).

[Here](https://github.com/Kaixhin/Rainbow/pull/49) is the link to the pull request

**Comment by Kaixhin** [comment]
Closed by #49
