### ISSUE TITLE
Hyper parameter

### ISSUE THREAD

**Issue by jiafei1224** [Kaixhin/Rainbow#56]
Can i check with you on the difference between the canonical parameter and the data efficient parameter? Can i say that the data efficient parameter are more likely recommended?

**Comment by Kaixhin** [comment]
You can refer to the data-efficient Rainbow paper for details, but the hyperparameters were tuned there to achieve high rewards quickly, which doesn't necessarily mean that the performance after a lot of experience will be as good as they were with the original hyperparameters. But if you want to be "data-efficient", then yes the new hyperparameters should be a better starting point.
