### ISSUE TITLE
Taking the max over step frame buffer

### ISSUE THREAD

**Issue by guydav** [Kaixhin/Rainbow#59]
Hey Kai,

I'm digging into the implementation details, and have another question about a particular detail. in Env.step(), you store the frames after the 3rd and 4th repetitions of the actions, and then take the pixel-wise max between the two as the observation. Why do you do that? Is there a particular paper this comes from?

Thank you!

**Comment by Kaixhin** [comment]
From the Methods of the Nature DQN paper:
> First, to encode a single frame we take the maximum value for each pixel colour value over the frame being encoded and the previous frame. This was necessary to remove flickering that is present in games where some objects appear only in even frames while other objects appear only in odd frames, an artefact caused by the limited number of sprites Atari 2600 can display at once.

**Comment by guydav** [comment]
Thank you! I don't know how I missed this, I definitely searched in that paper.
