### ISSUE TITLE
Infinite loop in ReplayMemory._get_sample_from_segment

### ISSUE THREAD

**Issue by luisenp** [Kaixhin/Rainbow#60]
I'm testing a variant of this code using the vizdoom environment and in some cases I see an infinite loop here https://github.com/Kaixhin/Rainbow/blob/master/memory.py#L103. I'm still not familiar with the code so not sure how to go about debugging this. Any pointers would be appreciated. (Note that I haven't changed any of the replay memory code).

Thanks.

**Comment by Kaixhin** [comment]
Duplicate of #41 . As noted there, it's an inherent problem with using PER, which can be resolved by setting hyperparameters appropriately for the domain.
