### ISSUE TITLE
rainbow for multiagent setting

### ISSUE THREAD

**Issue by zyzhang1130** [Kaixhin/Rainbow#62]
Hi, may I ask how should I apply rainbow for a multi-agent setting? I imagine that there should be two models to be trained and each model's reward depends on another agents reward (can be positively or negatively correlated). More importantly, the two models should be trained alternatively (i.e. iter1 train agent1, iter2 train agent2, iter3 train agent1, iter4 train agent2 so on and so forth) 

Thanks a lot.

**Comment by Kaixhin** [comment]
That setup certainly is one way of doing it, but there's many others. This isn't particular to Rainbow, so you should consult the many papers doing multiagent RL with the DQN/DDPG to see what is being done.

**Comment by zyzhang1130** [comment]
Hi, 
I checked a DDPG model but it seems their way of defining policy is different from rainbow, May I at least know under which script do you define the policy and how do you call them for each iteration?

Thank you.
