### ISSUE TITLE
Policy and reward function

### ISSUE THREAD

**Issue by zyzhang1130** [Kaixhin/Rainbow#63]
Hi,
There is certain thing I would like to modify for policy and reward function. May I ask where is policy stored after each epoch of training? Is there some way to call/index/assign it with some flag? 
Thanks for answering.

**Comment by Kaixhin** [comment]
The agent has an [`act`](https://github.com/Kaixhin/Rainbow/blob/master/agent.py#L51) method, and there's code for loading pretrained weights in [`__init__`](https://github.com/Kaixhin/Rainbow/blob/master/agent.py#L24-L31).

**Comment by zyzhang1130** [comment]
Do you mind to further elaborate what does act do and is the policy/model/weights saved after each epoch/iteration? If not how should I make it happen?

Thanks a lot.

**Comment by Kaixhin** [comment]
`act` predicts 1-of-k actions given a state, picking the action with the highest Q-value. The model weights are saved [every `checkpoint-interval`](https://github.com/Kaixhin/Rainbow/blob/master/main.py#L179-L181).

**Comment by zyzhang1130** [comment]
noted with thanks.
