### ISSUE TITLE
ploting the result

### ISSUE THREAD

**Issue by zyzhang1130** [Kaixhin/Rainbow#64]
Sorry I tried to run the test.py file in the hope of seeing some plot for the result but nothing came out. I checked test.py and realized neither _plot_line not test function was called. I also checked other .py files. It seems test is called in the main but I could not find _plot_line anywhere. May I know how should I plot the results if my training?

Thank you.

**Comment by Kaixhin** [comment]
If you run `main.py` it starts training, and it calls the `test` function from `test.py` which itself calls `_plot_line`, which is at the bottom of `test.py`.
