### ISSUE TITLE
Running Rainbow on a Cluster 

### ISSUE THREAD

**Issue by FarhaParveen919** [Kaixhin/Rainbow#72]
Dear Kai,

Thank you very much for having this repository. It is very useful and it was a great learning experience reading through the code. I have been able to run the rainbow code with the sample arguments provided in .README.md file. I want to now run the cases for larger T-max (e.g. 50e6) and memory-capacity (1e6) to replicate sizes comparable to the Deepmind paper on rainbow. 

I was wondering whether it would be possible to run the code on a cluster in order to reduce the runtime. If possible, it would be very helpful if you could advise on the arguments (to the main.py file) needed for running the code on cluster, and how to set the appropriate parameters in the job submission file (attached). 

Looking forward to your response !

Regards,
Farha Parveen

![pbsfile](https://user-images.githubusercontent.com/56920928/80314320-754d0180-87b6-11ea-869d-1dceb4386daf.png)

**Comment by Kaixhin** [comment]
Unfortunately I've never run this on a cluster and can't comment on the details of your cluster, but you can just use `python main.py` for the original Rainbow - the arguments provided in the README are for the data-efficient one. With your cluster you'll want to make sure you're using GPU, so talk to someone in your group/your IT support if you're unsure. In terms of RAM, you'll want at least 10GB, but you don't need lots of GPU memory - 4GB should suffice.
