### ISSUE TITLE
Evaluate the pretrained model

### ISSUE THREAD

**Issue by Yingdong-Hu** [Kaixhin/Rainbow#77]
Hi, I download the pretrained V1.3 pong model and want to evaluate it.
I run the following command: 
`python main.py --game pong --model pretrained/pong.pth --evaluate`
But the final average reward is only -21. What's the correct method to evaluate the pretrained model ? Thank you.

**Comment by Kaixhin** [comment]
I "fixed" the model architecture since the 1.3 release, and it turns out that this broke all the pretrained models. You need to make a small manual change, which is now detailed in the README.
