### ISSUE TITLE
Could you provide the correct sets of arguments for each agent types ?

### ISSUE THREAD

**Issue by k4ntz** [Kaixhin/Rainbow#87]
Hi ! Amazing work. Thank you for sharing it. :pray: 
I am trying to use your repo to reconduct experiments of my paper with cleaner implementations. I am adapting your code such that I can vary the activation function and look at the outcome. 

Could you give the set of arguments to use with the `main.py` such that one can run DQN and DDQN (i.e., how can one disable *Distributional RL* or *Noisy Net*). 

I have an idea on which arguments to use, but I'd like to be sure of the script I'm launching before I start varying the algorithms, activation functions and environments, as it will be probably results in months of GPU hours.

In advance, thank you very much.

**Comment by Kaixhin** [comment]
Unfortunately this code does not support that - it does not implement scalar (non-distributional) value functions etc. - so it is not possible to recreate the original DQN training settings just by adjusting the arguments. It would involve quite an extensive change to the codebase as this wasn't an intended use case.
